version: "3.9"  # optional since v1.27.0
services:

  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-script/postgres:/docker-entrypoint-initdb.d

  keycloak:
    image: jboss/keycloak:15.0.1
    container_name: keycloak
    depends_on:
      - postgresdb
    ports:
      - 8180:8180
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: postgres
      DB_PORT: 5432
      DB_USER: keycloak_user
      DB_PASSWORD: password
      DB_ADDR: postgresdb
      JAVA_OPTS_APPEND: "-Djboss.http.port=8180"
      KEYCLOAK_IMPORT: "/tmp/inventory-manager-api-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - ./init-script/keycloak:/tmp